### ISSUE TITLE
Use the IP networks (and domains) set aside specifically for documentation

### ISSUE THREAD

**Issue by brycied00d** [classam/buildatheweb#1]
[RFC5737](https://tools.ietf.org/html/rfc5737) sets aside 3 IPv4 networks specifically for use in documentation, guaranteed to not actually be anybody's anything (neither someone's website, nor your home router), and aren't even publicly routable so any "noise" you make won't impact the Internet.
Likewise, there is [RFC3849](https://tools.ietf.org/html/rfc3849) for IPv6 and [RFC6761](https://tools.ietf.org/html/rfc6761) for domains.

**Comment by cube-drone** [comment]
Out of the two IP addresses I generated by hand for this 

one of them was from a documentation network, because I figured there had to be one

and the other one was not, because I am a lazy dude

but you're right

**Comment by cube-drone** [comment]
on the other hand, I refuse to stop using 'butts.cash' as an example domain

**Comment by cube-drone** [comment]
wait, Plan B, I'm going to register a ridiculous domain and use it

**Comment by cube-drone** [comment]
Okay, mission accomplish: https://github.com/classam/buildatheweb/commit/24022d5bad28cbbcbdc40e6092ee1bfa89123ba6
